# To use: tmuxinator start project

name: project
root: <%= ENV['PWD'] %>

windows:
  - main:
      panes:
        - # First pane (will be top left)
        - # Second pane (right side, full height)
        - pane:
          - tmux select-pane -t 0  # Go back to first pane
          - tmux split-window -v   # Split it vertically (bottom left)

